//
//  File 2.swift
//  
//
//  Created by Michael Geurtjens on 17/12/2022.
//

import Foundation
public class WordListExamples {
    
    public static func Words_8702() -> [String] {
        return ["EMBEZZLE","GAZUMP","BUY","SQUEEZE","PROXY","TRUST","PAY","SPOT","BUYER","UNITS","PARITY","MONEY","CUT","TAX","ASSETS","LOSS","PAYMENT","TRUSTEE","COST","MONOPOLY","SHORT","BONUS","NOTES","QUOTE","PROSPECTUS","CURRENCY","INVESTMENT","IOU","TIP","STOCK","JUMP","DISCOUNT","INTEREST","SETTLEMENT","FUNDS","YIELD","NET","OPTION","RIGHTS","SECURITIES","REPORT","SHARES","DEPOSIT","LIABILITY","CONTRACT","ACCOUNT","PREMIUM","RESERVE","REVENUE","PROFIT","SCRIP","SOLD","VENDOR","MARKET","GUARANTEE","BOOM","BULL","SELL","DEBENTURE","AGENT","DRAWER","DEFAULT","CREDITOR","INFLATION","PAR","CASH","RING","SALE","CORNER","RECEIPT","CARTEL","CHEQUE","CREDIT","MARGIN","ORDER","FIRM","CAPITAL","PERCENTAGE","RIG","BROKER","INCOME","MERGER","DEBIT","COLLATERAL","AVERAGE","BOND","DIVIDEND","EXCHANGE","PRICE","ADVICE","GOLD","OFFER","BANKER","JOBBER","BANK","FINANCE","BEAR","BILL","BALANCE","CALL","BID","DEAL","DEED"]
    }
    
    
    public static func getWordList() -> [String] {
        return [            "ZION","AZURE","TOYS","JOY","HAZELNUT","NUTS","NAZARETH","HYMN","TURKEY","SNOW","MERRY","TOAST","STAR","HOLLY","JELLY","FAMILY","WHITE","SING","SAUCE","PORK","TREE","EVE","INN","BELLS","CAKE",
            
            "GLAZE","PARTYHATS","TWENTYFIFTH","WALNUT","PEANUTS","PRESENTS","FRUIT","NUTMEG","CUSTARD","CHRISTMAS","MISTLETOE","GIFTS","SANTACLAUS","FESTIVE","RAISINS","LIGHTS","WREATH","HOLIDAY","WISEMEN","CRANBERRY","OPENHOUSE","SILENTNIGHT","STOCKING","PUNCH","WINE","SHOPPING","PLUMPUDDING","WRAPPING","NEIGHBOURS","GREETINGS","DECORATIONS","ALMONDS","LANTERN","KRISSKRINGLE","SPICE","GOODWILL","BONBON","CHURCH","FRIENDS","PARCELS","CINNAMON","NICHOLAS","MINCEPIES","CHERRIES","SLEIGH","ALMOND","MANGER","RIBBON","CHOCOLATE","MIXEDPEEL","DRINK","CANDLES","FOOD","GINGER","BETHLEHEM","CAROL","REINDEER","GOODCHEER","CREAM","CORDIAL","CHILDREN","ICECREAM","CHICKEN","CARD","DECEMBER","PEACE"
        ]
    }
}
